-- MySQL Script generated by MySQL Workbench
-- Tue Nov  3 14:14:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ATM_management_system_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ATM_management_system_DB` ;

-- -----------------------------------------------------
-- Schema ATM_management_system_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ATM_management_system_DB` DEFAULT CHARACTER SET utf8 ;
USE `ATM_management_system_DB` ;

-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`User` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`User` (
  `user_id` TINYINT NOT NULL AUTO_INCREMENT,
  `last_login` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gov_issued_id` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NULL,
  `last_name` VARCHAR(15) NOT NULL,
  `first_name` VARCHAR(10) NOT NULL,
  `address` TINYINT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Phone_number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Phone_number` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Phone_number` (
  `phone_number_id` TINYINT NOT NULL AUTO_INCREMENT,
  `country_code` INT NOT NULL,
  `number` BIGINT(14) NOT NULL,
  `country` VARCHAR(2) NOT NULL,
  `user` TINYINT NULL,
  PRIMARY KEY (`phone_number_id`),
  INDEX `Phone_number_User_FK1_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `Phone_number_User_FK1`
    FOREIGN KEY (`user`)
    REFERENCES `ATM_management_system_DB`.`User` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Incident`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Incident` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Incident` (
  `incident_id` TINYINT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`incident_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Police_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Police_report` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Police_report` (
  `police_report_id` TINYINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user` TINYINT NOT NULL,
  `incident` TINYINT NULL,
  PRIMARY KEY (`police_report_id`),
  INDEX `Police_report_User_FK1_idx` (`user` ASC) VISIBLE,
  INDEX `Police_report_Incident_FK1_idx` (`incident` ASC) VISIBLE,
  CONSTRAINT `Police_report_User_FK`
    FOREIGN KEY (`user`)
    REFERENCES `ATM_management_system_DB`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Police_report_Incident_FK`
    FOREIGN KEY (`incident`)
    REFERENCES `ATM_management_system_DB`.`Incident` (`incident_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Address` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Address` (
  `address_id` TINYINT NOT NULL AUTO_INCREMENT,
  `street_address` VARCHAR(45) NOT NULL,
  `apt_number` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `zip_code` INT NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`User_Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`User_Address` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`User_Address` (
  `user_address_id` TINYINT NOT NULL AUTO_INCREMENT,
  `user` TINYINT NOT NULL,
  `address` TINYINT NOT NULL,
  PRIMARY KEY (`user_address_id`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC) VISIBLE,
  INDEX `User_Address_Address_FK_idx` (`address` ASC) VISIBLE,
  UNIQUE INDEX `address_UNIQUE` (`address` ASC) VISIBLE,
  CONSTRAINT `User_Address_User_FK`
    FOREIGN KEY (`user`)
    REFERENCES `ATM_management_system_DB`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `User_Address_Address_FK`
    FOREIGN KEY (`address`)
    REFERENCES `ATM_management_system_DB`.`Address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`ATM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`ATM` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`ATM` (
  `atm_id` TINYINT NOT NULL AUTO_INCREMENT,
  `money_available` DECIMAL(2) NOT NULL DEFAULT 0,
  `money_capacity` DECIMAL(2) NOT NULL DEFAULT 0,
  `address` TINYINT NULL,
  PRIMARY KEY (`atm_id`),
  INDEX `ATM_Adress_FK_idx` (`address` ASC) VISIBLE,
  CONSTRAINT `ATM_Address_FK`
    FOREIGN KEY (`address`)
    REFERENCES `ATM_management_system_DB`.`Address` (`address_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Phone_app`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Phone_app` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Phone_app` (
  `phone_app_id` TINYINT NOT NULL AUTO_INCREMENT,
  `login_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `safeEx_account` TINYINT NULL,
  PRIMARY KEY (`phone_app_id`),
  UNIQUE INDEX `safeEx_account_UNIQUE` (`safeEx_account` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Receipt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Receipt` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Receipt` (
  `receipt_id` TINYINT NOT NULL AUTO_INCREMENT,
  `issue_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `transaction` TINYINT NULL,
  PRIMARY KEY (`receipt_id`),
  UNIQUE INDEX `transaction_UNIQUE` (`transaction` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Bank_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Bank_account` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Bank_account` (
  `bank_account_id` TINYINT NOT NULL AUTO_INCREMENT,
  `account_number` BIGINT(8) ZEROFILL NOT NULL,
  `balance` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user` TINYINT NOT NULL,
  PRIMARY KEY (`bank_account_id`, `account_number`),
  UNIQUE INDEX `bank_account_id_UNIQUE` (`bank_account_id` ASC) VISIBLE,
  INDEX `Bank_account_User_FK1_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `Bank_account_User_FK`
    FOREIGN KEY (`user`)
    REFERENCES `ATM_management_system_DB`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Transaction` (
  `transaction_id` TINYINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `completed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `credential` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `amount` DECIMAL(5,2) NOT NULL,
  `receipt` TINYINT NULL,
  `sender` TINYINT NULL,
  `recipient` TINYINT NULL,
  `phone_app` TINYINT NULL,
  `atm` TINYINT NULL,
  `bank_account` TINYINT NULL,
  PRIMARY KEY (`transaction_id`),
  UNIQUE INDEX `receipt_UNIQUE` (`receipt` ASC) VISIBLE,
  UNIQUE INDEX `credential_UNIQUE` (`credential` ASC) VISIBLE,
  INDEX `Transaction_recipient_User_FK_idx` (`recipient` ASC) VISIBLE,
  INDEX `Transaction_sender_User_FK_idx` (`sender` ASC) VISIBLE,
  INDEX `Transaction_Phone_app_FK1_idx` (`phone_app` ASC) VISIBLE,
  INDEX `Transaction_ATM_FK1_idx` (`atm` ASC) VISIBLE,
  INDEX `Transaction_Bank_account_FK1_idx` (`bank_account` ASC) VISIBLE,
  CONSTRAINT `Transaction_Receipt_FK`
    FOREIGN KEY (`receipt`)
    REFERENCES `ATM_management_system_DB`.`Receipt` (`receipt_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Transaction_sender_User_FK`
    FOREIGN KEY (`sender`)
    REFERENCES `ATM_management_system_DB`.`User` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Transaction_recipient_User_FK`
    FOREIGN KEY (`recipient`)
    REFERENCES `ATM_management_system_DB`.`User` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Transaction_Phone_app_FK`
    FOREIGN KEY (`phone_app`)
    REFERENCES `ATM_management_system_DB`.`Phone_app` (`phone_app_id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT,
  CONSTRAINT `Transaction_ATM_FK`
    FOREIGN KEY (`atm`)
    REFERENCES `ATM_management_system_DB`.`ATM` (`atm_id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT,
  CONSTRAINT `Transaction_Bank_account_FK`
    FOREIGN KEY (`bank_account`)
    REFERENCES `ATM_management_system_DB`.`Bank_account` (`bank_account_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Payment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Payment_type` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Payment_type` (
  `payment_type_id` TINYINT NOT NULL AUTO_INCREMENT,
  `transaction` TINYINT NOT NULL,
  `paid_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_type_id`, `transaction`),
  UNIQUE INDEX `transaction_UNIQUE` (`transaction` ASC) VISIBLE,
  CONSTRAINT `payment_type_Transaction_FK`
    FOREIGN KEY (`transaction`)
    REFERENCES `ATM_management_system_DB`.`Transaction` (`transaction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Bank_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Bank_card` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Bank_card` (
  `bank_card_id` TINYINT NOT NULL AUTO_INCREMENT,
  `card_number` INT NOT NULL,
  `PIN` INT NOT NULL,
  `display_name` VARCHAR(45) NULL,
  `expiry_date` DATETIME NOT NULL,
  `card_type` VARCHAR(45) NOT NULL,
  `bank_account` TINYINT NOT NULL,
  PRIMARY KEY (`bank_card_id`, `bank_account`),
  UNIQUE INDEX `card_number_UNIQUE` (`card_number` ASC) VISIBLE,
  INDEX `Bank_card_Bank_account_FK1_idx` (`bank_account` ASC) VISIBLE,
  UNIQUE INDEX `bank_account_UNIQUE` (`bank_account` ASC) VISIBLE,
  CONSTRAINT `Bank_card_Bank_account_FK`
    FOREIGN KEY (`bank_account`)
    REFERENCES `ATM_management_system_DB`.`Bank_account` (`bank_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Currency` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Currency` (
  `currency_id` TINYINT NOT NULL AUTO_INCREMENT,
  `currency_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`currency_id`, `currency_name`),
  UNIQUE INDEX `currency_name_UNIQUE` (`currency_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Notification` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Notification` (
  `notification_id` TINYINT NOT NULL AUTO_INCREMENT,
  `sent_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `transaction` TINYINT NOT NULL,
  PRIMARY KEY (`notification_id`),
  INDEX `Notification_Transaction_FK1_idx` (`transaction` ASC) VISIBLE,
  CONSTRAINT `Notification_Transaction_FK1`
    FOREIGN KEY (`transaction`)
    REFERENCES `ATM_management_system_DB`.`Transaction` (`transaction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Security_footage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Security_footage` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Security_footage` (
  `security_footage_id` TINYINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `transaction` TINYINT NOT NULL,
  PRIMARY KEY (`security_footage_id`),
  INDEX `Security_footage_Transaction_FK1_idx` (`transaction` ASC) VISIBLE,
  CONSTRAINT `Security_footage_Transaction_FK`
    FOREIGN KEY (`transaction`)
    REFERENCES `ATM_management_system_DB`.`Transaction` (`transaction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Camera_angle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Camera_angle` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Camera_angle` (
  `camera_angle_id` TINYINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`camera_angle_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Cash`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Cash` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Cash` (
  `cash_id` TINYINT NOT NULL AUTO_INCREMENT,
  `amount_dispensed` VARCHAR(45) NOT NULL,
  `currency` TINYINT NULL,
  `payment_type` TINYINT NOT NULL,
  PRIMARY KEY (`cash_id`, `payment_type`),
  INDEX `Cash_Currency_FK_idx` (`currency` ASC) VISIBLE,
  INDEX `Cash_Payment_type_FK1_idx` (`payment_type` ASC) VISIBLE,
  CONSTRAINT `Cash_Currency_FK`
    FOREIGN KEY (`currency`)
    REFERENCES `ATM_management_system_DB`.`Currency` (`currency_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `Cash_Payment_type_FK`
    FOREIGN KEY (`payment_type`)
    REFERENCES `ATM_management_system_DB`.`Payment_type` (`payment_type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`SafeEx_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`SafeEx_account` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`SafeEx_account` (
  `safeex_account_id` TINYINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user` TINYINT NOT NULL,
  PRIMARY KEY (`safeex_account_id`),
  INDEX `SafeEx_account_User_FK1_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `SafeEx_account_User_FK1`
    FOREIGN KEY (`user`)
    REFERENCES `ATM_management_system_DB`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Credit_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Credit_card` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Credit_card` (
  `credit_card_id` TINYINT NOT NULL AUTO_INCREMENT,
  `payment_type` TINYINT NOT NULL,
  `bank_card` TINYINT NULL,
  PRIMARY KEY (`credit_card_id`, `payment_type`),
  INDEX `Credit_card_Payment_type_FK_idx` (`payment_type` ASC) VISIBLE,
  INDEX `Credit_card_Bank_card_FK1_idx` (`bank_card` ASC) VISIBLE,
  CONSTRAINT `Credit_card_Payment_type_FK`
    FOREIGN KEY (`payment_type`)
    REFERENCES `ATM_management_system_DB`.`Payment_type` (`payment_type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Credit_card_Bank_card_FK`
    FOREIGN KEY (`bank_card`)
    REFERENCES `ATM_management_system_DB`.`Bank_card` (`bank_card_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Debit_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Debit_card` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Debit_card` (
  `debit_card_id` TINYINT NOT NULL AUTO_INCREMENT,
  `payment_type` TINYINT NOT NULL,
  `bank_card` TINYINT NULL,
  PRIMARY KEY (`debit_card_id`, `payment_type`),
  INDEX `Credit_card_Payment_type_FK_idx` (`payment_type` ASC) VISIBLE,
  INDEX `Debit_card_Bank_card_FK1_idx` (`bank_card` ASC) VISIBLE,
  CONSTRAINT `Debit_card_Payment_type_FK`
    FOREIGN KEY (`payment_type`)
    REFERENCES `ATM_management_system_DB`.`Payment_type` (`payment_type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Debit_card_Bank_card_FK`
    FOREIGN KEY (`bank_card`)
    REFERENCES `ATM_management_system_DB`.`Bank_card` (`bank_card_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Recordings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Recordings` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Recordings` (
  `security_footage` TINYINT NOT NULL AUTO_INCREMENT,
  `camera_angle` TINYINT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`security_footage`, `camera_angle`),
  INDEX `Security_footage_has_Camera_angle_Camera_angle_FK1_idx` (`camera_angle` ASC) VISIBLE,
  INDEX `Security_footage_has_Camera_angle_Security_footage_FK1_idx` (`security_footage` ASC) VISIBLE,
  CONSTRAINT `Security_footage_has_Camera_angle_Security_footage_FK1`
    FOREIGN KEY (`security_footage`)
    REFERENCES `ATM_management_system_DB`.`Security_footage` (`security_footage_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Security_footage_has_Camera_angle_Camera_angle_FK1`
    FOREIGN KEY (`camera_angle`)
    REFERENCES `ATM_management_system_DB`.`Camera_angle` (`camera_angle_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM_management_system_DB`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM_management_system_DB`.`Login` ;

CREATE TABLE IF NOT EXISTS `ATM_management_system_DB`.`Login` (
  `safeex_account` TINYINT NOT NULL,
  `user` TINYINT NOT NULL,
  `login_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`safeex_account`, `user`),
  INDEX `SafeEx_account_has_User_User_FK1_idx` (`user` ASC) VISIBLE,
  INDEX `SafeEx_account_has_User_SafeEx_account_FK1_idx` (`safeex_account` ASC) VISIBLE,
  CONSTRAINT `SafeEx_account_has_User_SafeEx_account_FK1`
    FOREIGN KEY (`safeex_account`)
    REFERENCES `ATM_management_system_DB`.`SafeEx_account` (`safeex_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SafeEx_account_has_User_User_FK1`
    FOREIGN KEY (`user`)
    REFERENCES `ATM_management_system_DB`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
